/**
 * Configure Monaco for Electron + Vite without CDN.
 * Themes: light, light-modern, dark (zinc+sand), dark-modern.
 */
import { loader } from "@monaco-editor/react";
import * as monaco from "monaco-editor";
import editorWorker from "monaco-editor/esm/vs/editor/editor.worker?worker";
import cssWorker from "monaco-editor/esm/vs/language/css/css.worker?worker";
import htmlWorker from "monaco-editor/esm/vs/language/html/html.worker?worker";
import jsonWorker from "monaco-editor/esm/vs/language/json/json.worker?worker";
import tsWorker from "monaco-editor/esm/vs/language/typescript/ts.worker?worker";

let configured = false;
let themesRegistered = false;

function registerAnchorThemes(m: typeof monaco): void {
  if (themesRegistered) return;
  themesRegistered = true;

  // Surfaces match shell --bg-panel (#171718); syntax = VS Code Dark Modern tokens.
  m.editor.defineTheme("anchor-dark", {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "d4d4d4", background: "171718" },
      { token: "comment", foreground: "6a9955", fontStyle: "italic" },
      { token: "string", foreground: "ce9178" },
      { token: "string.escape", foreground: "d7ba7d" },
      { token: "keyword", foreground: "569cd6" },
      { token: "keyword.control", foreground: "c586c0" },
      { token: "number", foreground: "b5cea8" },
      { token: "regexp", foreground: "d16969" },
      { token: "type", foreground: "4ec9b0" },
      { token: "class", foreground: "4ec9b0" },
      { token: "interface", foreground: "4ec9b0" },
      { token: "struct", foreground: "4ec9b0" },
      { token: "enum", foreground: "4ec9b0" },
      { token: "typeParameter", foreground: "4ec9b0" },
      { token: "function", foreground: "dcdcaa" },
      { token: "method", foreground: "dcdcaa" },
      { token: "member", foreground: "dcdcaa" },
      { token: "variable", foreground: "9cdcfe" },
      { token: "parameter", foreground: "9cdcfe" },
      { token: "property", foreground: "9cdcfe" },
      { token: "constant", foreground: "4fc1ff" },
      { token: "operator", foreground: "d4d4d4" },
      { token: "delimiter", foreground: "d4d4d4" },
      { token: "tag", foreground: "569cd6" },
      { token: "attribute.name", foreground: "9cdcfe" },
      { token: "attribute.value", foreground: "ce9178" },
      { token: "meta.preprocessor", foreground: "c586c0" },
      { token: "annotation", foreground: "dcdcaa" },
      { token: "emphasis", fontStyle: "italic" },
      { token: "strong", fontStyle: "bold" },
    ],
    colors: {
      // Editor chrome follows shell zinc (not VS Code blue workbench)
      "editor.background": "#171718",
      "editor.foreground": "#d4d4d4",
      "editorLineNumber.foreground": "#5a5a60",
      "editorLineNumber.activeForeground": "#a8a8ad",
      "editorCursor.foreground": "#d2b48c",
      // Warm sand selection / highlights (not blue)
      "editor.selectionBackground": "#3a342680",
      "editor.inactiveSelectionBackground": "#2c292255",
      "editor.lineHighlightBackground": "#1e1e2080",
      "editor.lineHighlightBorder": "#00000000",
      "editor.wordHighlightBackground": "#3a342655",
      "editor.wordHighlightStrongBackground": "#3a342680",
      "editor.findMatchBackground": "#6b5a3a88",
      "editor.findMatchHighlightBackground": "#6b5a3a55",
      "editorIndentGuide.background": "#2e2e32",
      "editorIndentGuide.activeBackground": "#3f3f44",
      "editorWidget.background": "#171718",
      "editorWidget.border": "#2e2e32",
      "editorWidget.foreground": "#ececec",
      "editorSuggestWidget.background": "#171718",
      "editorSuggestWidget.border": "#2e2e32",
      "editorSuggestWidget.selectedBackground": "#2c2922",
      "editorSuggestWidget.foreground": "#ececec",
      "editorHoverWidget.background": "#171718",
      "editorHoverWidget.border": "#2e2e32",
      "editorHoverWidget.foreground": "#ececec",
      "menu.background": "#171718",
      "menu.foreground": "#a8a8ad",
      "menu.border": "#2e2e32",
      "menu.separatorBackground": "#2e2e32",
      "menu.selectionBackground": "#2c2922",
      "menu.selectionForeground": "#d2b48c",
      "menu.selectionBorder": "#00000000",
      "list.hoverBackground": "#1e1e20",
      "list.activeSelectionBackground": "#2c2922",
      "list.activeSelectionForeground": "#d2b48c",
      "list.focusBackground": "#2c2922",
      "list.focusForeground": "#d2b48c",
      "list.inactiveSelectionBackground": "#1e1e20",
      "list.inactiveSelectionForeground": "#ececec",
      "editorActionList.background": "#171718",
      "editorActionList.foreground": "#a8a8ad",
      "editorActionList.focusBackground": "#2c2922",
      "editorActionList.focusForeground": "#d2b48c",
      "widget.shadow": "#00000066",
      "scrollbarSlider.background": "#3f3f4466",
      "scrollbarSlider.hoverBackground": "#3f3f4499",
      "scrollbarSlider.activeBackground": "#3f3f44cc",
      "minimap.background": "#171718",
      "diffEditor.insertedTextBackground": "#2a403580",
      "diffEditor.removedTextBackground": "#4a282880",
      "diffEditor.insertedLineBackground": "#1a2e2480",
      "diffEditor.removedLineBackground": "#3a222280",
      "editorGutter.background": "#171718",
      "editorOverviewRuler.border": "#00000000",
      "editorBracketMatch.background": "#3a342640",
      "editorBracketMatch.border": "#a89060",
    },
  });

  
  // Full VS Code Dark Modern workbench + syntax
  m.editor.defineTheme("anchor-dark-modern", {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "cccccc", background: "1f1f1f" },
      { token: "comment", foreground: "6a9955", fontStyle: "italic" },
      { token: "string", foreground: "ce9178" },
      { token: "string.escape", foreground: "d7ba7d" },
      { token: "keyword", foreground: "569cd6" },
      { token: "keyword.control", foreground: "c586c0" },
      { token: "number", foreground: "b5cea8" },
      { token: "regexp", foreground: "d16969" },
      { token: "type", foreground: "4ec9b0" },
      { token: "class", foreground: "4ec9b0" },
      { token: "interface", foreground: "4ec9b0" },
      { token: "struct", foreground: "4ec9b0" },
      { token: "enum", foreground: "4ec9b0" },
      { token: "typeParameter", foreground: "4ec9b0" },
      { token: "function", foreground: "dcdcaa" },
      { token: "method", foreground: "dcdcaa" },
      { token: "member", foreground: "dcdcaa" },
      { token: "variable", foreground: "9cdcfe" },
      { token: "parameter", foreground: "9cdcfe" },
      { token: "property", foreground: "9cdcfe" },
      { token: "constant", foreground: "4fc1ff" },
      { token: "operator", foreground: "d4d4d4" },
      { token: "delimiter", foreground: "d4d4d4" },
      { token: "tag", foreground: "569cd6" },
      { token: "attribute.name", foreground: "9cdcfe" },
      { token: "attribute.value", foreground: "ce9178" },
      { token: "meta.preprocessor", foreground: "c586c0" },
      { token: "annotation", foreground: "dcdcaa" },
      { token: "emphasis", fontStyle: "italic" },
      { token: "strong", fontStyle: "bold" },
    ],
    colors: {
      "editor.background": "#1f1f1f",
      "editor.foreground": "#cccccc",
      "editorLineNumber.foreground": "#6e7681",
      "editorLineNumber.activeForeground": "#cccccc",
      "editorCursor.foreground": "#aeafad",
      "editor.selectionBackground": "#264f78",
      "editor.inactiveSelectionBackground": "#3a3d41",
      "editor.lineHighlightBackground": "#2a2d2e",
      "editor.lineHighlightBorder": "#00000000",
      "editor.wordHighlightBackground": "#575757b8",
      "editor.wordHighlightStrongBackground": "#004972b8",
      "editor.findMatchBackground": "#515c6a",
      "editor.findMatchHighlightBackground": "#ea5c0055",
      "editorIndentGuide.background": "#404040",
      "editorIndentGuide.activeBackground": "#707070",
      "editorWidget.background": "#1f1f1f",
      "editorWidget.border": "#3c3c3c",
      "editorWidget.foreground": "#cccccc",
      "editorSuggestWidget.background": "#1f1f1f",
      "editorSuggestWidget.border": "#3c3c3c",
      "editorSuggestWidget.selectedBackground": "#04395e",
      "editorSuggestWidget.foreground": "#cccccc",
      "editorHoverWidget.background": "#1f1f1f",
      "editorHoverWidget.border": "#3c3c3c",
      "editorHoverWidget.foreground": "#cccccc",
      "menu.background": "#1f1f1f",
      "menu.foreground": "#cccccc",
      "menu.border": "#3c3c3c",
      "menu.separatorBackground": "#2b2b2b",
      "menu.selectionBackground": "#04395e",
      "menu.selectionForeground": "#ffffff",
      "menu.selectionBorder": "#00000000",
      "list.hoverBackground": "#2a2d2e",
      "list.activeSelectionBackground": "#04395e",
      "list.activeSelectionForeground": "#ffffff",
      "list.focusBackground": "#04395e",
      "list.focusForeground": "#ffffff",
      "list.inactiveSelectionBackground": "#37373d",
      "list.inactiveSelectionForeground": "#cccccc",
      "editorActionList.background": "#1f1f1f",
      "editorActionList.foreground": "#cccccc",
      "editorActionList.focusBackground": "#04395e",
      "editorActionList.focusForeground": "#ffffff",
      "widget.shadow": "#00000080",
      "scrollbarSlider.background": "#79797966",
      "scrollbarSlider.hoverBackground": "#646464b3",
      "scrollbarSlider.activeBackground": "#bfbfbf66",
      "minimap.background": "#1f1f1f",
      "diffEditor.insertedTextBackground": "#9ccc2c33",
      "diffEditor.removedTextBackground": "#ff000033",
      "diffEditor.insertedLineBackground": "#9ccc2c22",
      "diffEditor.removedLineBackground": "#ff000022",
      "editorGutter.background": "#1f1f1f",
      "editorOverviewRuler.border": "#00000000",
      "editorBracketMatch.background": "#0064001a",
      "editorBracketMatch.border": "#888888",
    },
  });


  // VS Code Light Modern workbench + syntax (symmetric to dark-modern)
  m.editor.defineTheme("anchor-light-modern", {
    base: "vs",
    inherit: true,
    rules: [
      { token: "", foreground: "000000", background: "ffffff" },
      { token: "comment", foreground: "008000", fontStyle: "italic" },
      { token: "string", foreground: "a31515" },
      { token: "string.escape", foreground: "ee0000" },
      { token: "keyword", foreground: "0000ff" },
      { token: "keyword.control", foreground: "af00db" },
      { token: "number", foreground: "098658" },
      { token: "regexp", foreground: "811f3f" },
      { token: "type", foreground: "267f99" },
      { token: "class", foreground: "267f99" },
      { token: "interface", foreground: "267f99" },
      { token: "struct", foreground: "267f99" },
      { token: "enum", foreground: "267f99" },
      { token: "typeParameter", foreground: "267f99" },
      { token: "function", foreground: "795e26" },
      { token: "method", foreground: "795e26" },
      { token: "member", foreground: "795e26" },
      { token: "variable", foreground: "001080" },
      { token: "parameter", foreground: "001080" },
      { token: "property", foreground: "001080" },
      { token: "constant", foreground: "0070c1" },
      { token: "operator", foreground: "000000" },
      { token: "delimiter", foreground: "000000" },
      { token: "tag", foreground: "800000" },
      { token: "attribute.name", foreground: "e50000" },
      { token: "attribute.value", foreground: "0000ff" },
      { token: "meta.preprocessor", foreground: "af00db" },
      { token: "annotation", foreground: "795e26" },
      { token: "emphasis", fontStyle: "italic" },
      { token: "strong", fontStyle: "bold" },
    ],
    colors: {
      "editor.background": "#ffffff",
      "editor.foreground": "#3b3b3b",
      "editorLineNumber.foreground": "#6e7681",
      "editorLineNumber.activeForeground": "#171184",
      "editorCursor.foreground": "#000000",
      "editor.selectionBackground": "#add6ff",
      "editor.inactiveSelectionBackground": "#e5ebf1",
      "editor.lineHighlightBackground": "#f3f3f3",
      "editor.lineHighlightBorder": "#00000000",
      "editor.wordHighlightBackground": "#57575740",
      "editor.wordHighlightStrongBackground": "#0e639c40",
      "editor.findMatchBackground": "#a8ac94",
      "editor.findMatchHighlightBackground": "#ea5c0055",
      "editorIndentGuide.background": "#d3d3d3",
      "editorIndentGuide.activeBackground": "#939393",
      "editorWidget.background": "#f3f3f3",
      "editorWidget.border": "#cecece",
      "editorWidget.foreground": "#3b3b3b",
      "editorSuggestWidget.background": "#f3f3f3",
      "editorSuggestWidget.border": "#cecece",
      "editorSuggestWidget.selectedBackground": "#e8e8e8",
      "editorSuggestWidget.foreground": "#3b3b3b",
      "editorHoverWidget.background": "#f3f3f3",
      "editorHoverWidget.border": "#cecece",
      "editorHoverWidget.foreground": "#3b3b3b",
      "menu.background": "#ffffff",
      "menu.foreground": "#3b3b3b",
      "menu.border": "#cecece",
      "menu.separatorBackground": "#e5e5e5",
      "menu.selectionBackground": "#0060c0",
      "menu.selectionForeground": "#ffffff",
      "menu.selectionBorder": "#00000000",
      "list.hoverBackground": "#e8e8e8",
      "list.activeSelectionBackground": "#0060c0",
      "list.activeSelectionForeground": "#ffffff",
      "list.focusBackground": "#0060c0",
      "list.focusForeground": "#ffffff",
      "list.inactiveSelectionBackground": "#e4e6f1",
      "list.inactiveSelectionForeground": "#3b3b3b",
      "editorActionList.background": "#ffffff",
      "editorActionList.foreground": "#3b3b3b",
      "editorActionList.focusBackground": "#0060c0",
      "editorActionList.focusForeground": "#ffffff",
      "widget.shadow": "#00000029",
      "scrollbarSlider.background": "#64646466",
      "scrollbarSlider.hoverBackground": "#646464b3",
      "scrollbarSlider.activeBackground": "#00000066",
      "minimap.background": "#ffffff",
      "diffEditor.insertedTextBackground": "#9ccc2c40",
      "diffEditor.removedTextBackground": "#ff000033",
      "diffEditor.insertedLineBackground": "#9ccc2c22",
      "diffEditor.removedLineBackground": "#ff000022",
      "editorGutter.background": "#ffffff",
      "editorOverviewRuler.border": "#00000000",
      "editorBracketMatch.background": "#0064001a",
      "editorBracketMatch.border": "#b9b9b9",
    },
  });

m.editor.defineTheme("anchor-light", {
    base: "vs",
    inherit: true,
    rules: [],
    colors: {
      "editor.background": "#faf9f7",
      "editor.foreground": "#1c1b19",
      "editorLineNumber.foreground": "#a8a39a",
      "editorLineNumber.activeForeground": "#5c5954",
      "editorCursor.foreground": "#8a6a2f",
      "editor.selectionBackground": "#e8d9b580",
      "editor.inactiveSelectionBackground": "#e8e4db66",
      "editor.lineHighlightBackground": "#eceae680",
      "editor.lineHighlightBorder": "#00000000",
      "editorIndentGuide.background": "#ddd9d1",
      "editorIndentGuide.activeBackground": "#c9c3b8",
      "editorWidget.background": "#faf9f7",
      "editorWidget.border": "#ddd9d1",
      "editorWidget.foreground": "#1c1b19",
      "editorSuggestWidget.background": "#faf9f7",
      "editorSuggestWidget.border": "#ddd9d1",
      "editorSuggestWidget.selectedBackground": "#e8e4db",
      "editorSuggestWidget.foreground": "#1c1b19",
      "editorHoverWidget.background": "#faf9f7",
      "editorHoverWidget.border": "#ddd9d1",
      "editorHoverWidget.foreground": "#1c1b19",
      "menu.background": "#faf9f7",
      "menu.foreground": "#5c5954",
      "menu.border": "#ddd9d1",
      "menu.separatorBackground": "#ddd9d1",
      "menu.selectionBackground": "#e8e4db",
      "menu.selectionForeground": "#5c5954",
      "menu.selectionBorder": "#00000000",
      "list.hoverBackground": "#eceae6",
      "list.activeSelectionBackground": "#e8e4db",
      "list.activeSelectionForeground": "#5c5954",
      "list.focusBackground": "#e8e4db",
      "list.focusForeground": "#5c5954",
      "list.inactiveSelectionBackground": "#eceae6",
      "list.inactiveSelectionForeground": "#1c1b19",
      "editorActionList.background": "#faf9f7",
      "editorActionList.foreground": "#5c5954",
      "editorActionList.focusBackground": "#e8e4db",
      "editorActionList.focusForeground": "#5c5954",
      "widget.shadow": "#1c1b1926",
      "scrollbarSlider.background": "#c9c3b866",
      "scrollbarSlider.hoverBackground": "#c9c3b899",
      "scrollbarSlider.activeBackground": "#c9c3b8cc",
      "minimap.background": "#faf9f7",
      "diffEditor.insertedTextBackground": "#d1fae580",
      "diffEditor.removedTextBackground": "#fee2e280",
      "diffEditor.insertedLineBackground": "#ecfdf580",
      "diffEditor.removedLineBackground": "#fef2f280",
      "editorGutter.background": "#faf9f7",
      "editorOverviewRuler.border": "#00000000",
    },
  });
}

export function ensureMonacoConfigured(): void {
  if (configured) return;
  configured = true;

  self.MonacoEnvironment = {
    getWorker(_moduleId: string, label: string) {
      if (label === "json") return new jsonWorker();
      if (label === "css" || label === "scss" || label === "less") {
        return new cssWorker();
      }
      if (label === "html" || label === "handlebars" || label === "razor") {
        return new htmlWorker();
      }
      if (label === "typescript" || label === "javascript") {
        return new tsWorker();
      }
      return new editorWorker();
    },
  };

  loader.config({ monaco });
  registerAnchorThemes(monaco);
}

// Configure as soon as this module is imported.
ensureMonacoConfigured();
