/**
 * Configure Monaco for Electron + Vite without CDN.
 * Themes: light, light-modern, dark (zinc+sand), dark-modern.
 * Extra: richer C/C++ Monarch tokens so variables / types / functions color
 * without a full LSP.
 */
import { loader } from "@monaco-editor/react";
import * as monaco from "monaco-editor";
import editorWorker from "monaco-editor/esm/vs/editor/editor.worker?worker";
import cssWorker from "monaco-editor/esm/vs/language/css/css.worker?worker";
import htmlWorker from "monaco-editor/esm/vs/language/html/html.worker?worker";
import jsonWorker from "monaco-editor/esm/vs/language/json/json.worker?worker";
import tsWorker from "monaco-editor/esm/vs/language/typescript/ts.worker?worker";

let configured = false;
let themesRegistered = false;

/** VS Code Dark+ / Dark Modern syntax palette. */
const DARK_SYNTAX: monaco.editor.ITokenThemeRule[] = [
  { token: "", foreground: "d4d4d4" },
  { token: "identifier", foreground: "9cdcfe" },
  { token: "variable", foreground: "9cdcfe" },
  { token: "parameter", foreground: "9cdcfe" },
  { token: "property", foreground: "9cdcfe" },
  { token: "member", foreground: "9cdcfe" },
  { token: "constant", foreground: "4fc1ff" },
  { token: "comment", foreground: "6a9955", fontStyle: "italic" },
  { token: "comment.doc", foreground: "6a9955", fontStyle: "italic" },
  { token: "comment.line", foreground: "6a9955", fontStyle: "italic" },
  { token: "comment.block", foreground: "6a9955", fontStyle: "italic" },
  { token: "string", foreground: "ce9178" },
  { token: "string.escape", foreground: "d7ba7d" },
  { token: "string.invalid", foreground: "f44747" },
  { token: "string.raw", foreground: "ce9178" },
  { token: "string.raw.begin", foreground: "ce9178" },
  { token: "string.raw.end", foreground: "ce9178" },
  { token: "string.quote", foreground: "ce9178" },
  { token: "keyword.directive", foreground: "c586c0" },
  { token: "keyword.directive.control", foreground: "c586c0" },
  { token: "keyword.directive.include", foreground: "c586c0" },
  { token: "keyword.directive.include.begin", foreground: "c586c0" },
  { token: "keyword.directive.include.end", foreground: "ce9178" },
  { token: "meta.preprocessor", foreground: "c586c0" },
  { token: "keyword", foreground: "569cd6" },
  { token: "keyword.control", foreground: "c586c0" },
  { token: "keyword.operator", foreground: "d4d4d4" },
  { token: "storage", foreground: "569cd6" },
  { token: "storage.type", foreground: "569cd6" },
  { token: "storage.modifier", foreground: "569cd6" },
  { token: "number", foreground: "b5cea8" },
  { token: "number.hex", foreground: "b5cea8" },
  { token: "number.octal", foreground: "b5cea8" },
  { token: "number.binary", foreground: "b5cea8" },
  { token: "number.float", foreground: "b5cea8" },
  { token: "type", foreground: "4ec9b0" },
  { token: "type.identifier", foreground: "4ec9b0" },
  { token: "class", foreground: "4ec9b0" },
  { token: "struct", foreground: "4ec9b0" },
  { token: "interface", foreground: "4ec9b0" },
  { token: "enum", foreground: "4ec9b0" },
  { token: "namespace", foreground: "4ec9b0" },
  { token: "typeParameter", foreground: "4ec9b0" },
  { token: "function", foreground: "dcdcaa" },
  { token: "method", foreground: "dcdcaa" },
  { token: "support.function", foreground: "dcdcaa" },
  { token: "macro", foreground: "4fc1ff" },
  { token: "entity.name.function.preprocessor", foreground: "c586c0" },
  { token: "delimiter", foreground: "d4d4d4" },
  { token: "delimiter.bracket", foreground: "ffd700" },
  { token: "delimiter.parenthesis", foreground: "d4d4d4" },
  { token: "delimiter.square", foreground: "d4d4d4" },
  { token: "delimiter.angle", foreground: "d4d4d4" },
  { token: "operator", foreground: "d4d4d4" },
  { token: "annotation", foreground: "dcdcaa" },
  { token: "tag", foreground: "569cd6" },
  { token: "metatag", foreground: "569cd6" },
  { token: "attribute.name", foreground: "9cdcfe" },
  { token: "attribute.value", foreground: "ce9178" },
  { token: "regexp", foreground: "d16969" },
  { token: "emphasis", fontStyle: "italic" },
  { token: "strong", fontStyle: "bold" },
  { token: "enumMember", foreground: "4fc1ff" },
];

/** VS Code Light+ syntax palette. */
const LIGHT_SYNTAX: monaco.editor.ITokenThemeRule[] = [
  { token: "", foreground: "000000" },
  { token: "identifier", foreground: "001080" },
  { token: "variable", foreground: "001080" },
  { token: "parameter", foreground: "001080" },
  { token: "property", foreground: "001080" },
  { token: "member", foreground: "001080" },
  { token: "constant", foreground: "0070c1" },
  { token: "comment", foreground: "008000", fontStyle: "italic" },
  { token: "comment.doc", foreground: "008000", fontStyle: "italic" },
  { token: "comment.line", foreground: "008000", fontStyle: "italic" },
  { token: "comment.block", foreground: "008000", fontStyle: "italic" },
  { token: "string", foreground: "a31515" },
  { token: "string.escape", foreground: "ee0000" },
  { token: "string.invalid", foreground: "cd3131" },
  { token: "string.raw", foreground: "a31515" },
  { token: "keyword.directive", foreground: "af00db" },
  { token: "keyword.directive.control", foreground: "af00db" },
  { token: "keyword.directive.include", foreground: "af00db" },
  { token: "keyword.directive.include.begin", foreground: "af00db" },
  { token: "keyword.directive.include.end", foreground: "a31515" },
  { token: "meta.preprocessor", foreground: "af00db" },
  { token: "keyword", foreground: "0000ff" },
  { token: "keyword.control", foreground: "af00db" },
  { token: "keyword.operator", foreground: "000000" },
  { token: "storage", foreground: "0000ff" },
  { token: "storage.type", foreground: "0000ff" },
  { token: "storage.modifier", foreground: "0000ff" },
  { token: "number", foreground: "098658" },
  { token: "number.hex", foreground: "098658" },
  { token: "number.octal", foreground: "098658" },
  { token: "number.binary", foreground: "098658" },
  { token: "number.float", foreground: "098658" },
  { token: "type", foreground: "267f99" },
  { token: "type.identifier", foreground: "267f99" },
  { token: "class", foreground: "267f99" },
  { token: "struct", foreground: "267f99" },
  { token: "interface", foreground: "267f99" },
  { token: "enum", foreground: "267f99" },
  { token: "namespace", foreground: "267f99" },
  { token: "typeParameter", foreground: "267f99" },
  { token: "function", foreground: "795e26" },
  { token: "method", foreground: "795e26" },
  { token: "support.function", foreground: "795e26" },
  { token: "macro", foreground: "0070c1" },
  { token: "entity.name.function.preprocessor", foreground: "af00db" },
  { token: "delimiter", foreground: "000000" },
  { token: "delimiter.bracket", foreground: "0431fa" },
  { token: "delimiter.parenthesis", foreground: "000000" },
  { token: "delimiter.square", foreground: "000000" },
  { token: "operator", foreground: "000000" },
  { token: "annotation", foreground: "795e26" },
  { token: "tag", foreground: "800000" },
  { token: "metatag", foreground: "800000" },
  { token: "attribute.name", foreground: "e50000" },
  { token: "attribute.value", foreground: "0000ff" },
  { token: "regexp", foreground: "811f3f" },
  { token: "enumMember", foreground: "0070c1" },
];

const DARK_CHROME: monaco.editor.IColors = {
  "editor.background": "#171718",
  "editor.foreground": "#d4d4d4",
  "editorLineNumber.foreground": "#5a5a60",
  "editorLineNumber.activeForeground": "#a8a8ad",
  "editorCursor.foreground": "#d2b48c",
  "editor.selectionBackground": "#3a342680",
  "editor.inactiveSelectionBackground": "#2c292255",
  "editor.lineHighlightBackground": "#1e1e2080",
  "editor.lineHighlightBorder": "#00000000",
  "editor.wordHighlightBackground": "#3a342655",
  "editor.wordHighlightStrongBackground": "#3a342680",
  "editor.findMatchBackground": "#6b5a3a88",
  "editor.findMatchHighlightBackground": "#6b5a3a55",
  "editorIndentGuide.background": "#2e2e32",
  "editorIndentGuide.activeBackground": "#3f3f44",
  "editorWidget.background": "#171718",
  "editorWidget.border": "#2e2e32",
  "editorWidget.foreground": "#ececec",
  "editorSuggestWidget.background": "#171718",
  "editorSuggestWidget.border": "#2e2e32",
  "editorSuggestWidget.selectedBackground": "#2c2922",
  "editorSuggestWidget.foreground": "#ececec",
  "editorHoverWidget.background": "#171718",
  "editorHoverWidget.border": "#2e2e32",
  "editorHoverWidget.foreground": "#ececec",
  "menu.background": "#171718",
  "menu.foreground": "#a8a8ad",
  "menu.border": "#2e2e32",
  "menu.separatorBackground": "#2e2e32",
  "menu.selectionBackground": "#2c2922",
  "menu.selectionForeground": "#d2b48c",
  "menu.selectionBorder": "#00000000",
  "list.hoverBackground": "#1e1e20",
  "list.activeSelectionBackground": "#2c2922",
  "list.activeSelectionForeground": "#d2b48c",
  "list.focusBackground": "#2c2922",
  "list.focusForeground": "#d2b48c",
  "list.inactiveSelectionBackground": "#1e1e20",
  "list.inactiveSelectionForeground": "#ececec",
  "editorActionList.background": "#171718",
  "editorActionList.foreground": "#a8a8ad",
  "editorActionList.focusBackground": "#2c2922",
  "editorActionList.focusForeground": "#d2b48c",
  "widget.shadow": "#00000066",
  "scrollbarSlider.background": "#3f3f4466",
  "scrollbarSlider.hoverBackground": "#3f3f4499",
  "scrollbarSlider.activeBackground": "#3f3f44cc",
  "minimap.background": "#171718",
  "diffEditor.insertedTextBackground": "#2a403580",
  "diffEditor.removedTextBackground": "#4a282880",
  "diffEditor.insertedLineBackground": "#1a2e2480",
  "diffEditor.removedLineBackground": "#3a222280",
  "editorGutter.background": "#171718",
  "editorOverviewRuler.border": "#00000000",
  "editorBracketMatch.background": "#3a342640",
  "editorBracketMatch.border": "#a89060",
};

const DARK_MODERN_CHROME: monaco.editor.IColors = {
  "editor.background": "#1f1f1f",
  "editor.foreground": "#cccccc",
  "editorLineNumber.foreground": "#6e7681",
  "editorLineNumber.activeForeground": "#cccccc",
  "editorCursor.foreground": "#aeafad",
  "editor.selectionBackground": "#264f78",
  "editor.inactiveSelectionBackground": "#3a3d41",
  "editor.lineHighlightBackground": "#2a2d2e",
  "editor.lineHighlightBorder": "#00000000",
  "editor.wordHighlightBackground": "#575757b8",
  "editor.wordHighlightStrongBackground": "#004972b8",
  "editor.findMatchBackground": "#515c6a",
  "editor.findMatchHighlightBackground": "#ea5c0055",
  "editorIndentGuide.background": "#404040",
  "editorIndentGuide.activeBackground": "#707070",
  "editorWidget.background": "#1f1f1f",
  "editorWidget.border": "#3c3c3c",
  "editorWidget.foreground": "#cccccc",
  "editorSuggestWidget.background": "#1f1f1f",
  "editorSuggestWidget.border": "#3c3c3c",
  "editorSuggestWidget.selectedBackground": "#04395e",
  "editorSuggestWidget.foreground": "#cccccc",
  "editorHoverWidget.background": "#1f1f1f",
  "editorHoverWidget.border": "#3c3c3c",
  "editorHoverWidget.foreground": "#cccccc",
  "menu.background": "#1f1f1f",
  "menu.foreground": "#cccccc",
  "menu.border": "#3c3c3c",
  "menu.separatorBackground": "#2b2b2b",
  "menu.selectionBackground": "#04395e",
  "menu.selectionForeground": "#ffffff",
  "menu.selectionBorder": "#00000000",
  "list.hoverBackground": "#2a2d2e",
  "list.activeSelectionBackground": "#04395e",
  "list.activeSelectionForeground": "#ffffff",
  "list.focusBackground": "#04395e",
  "list.focusForeground": "#ffffff",
  "list.inactiveSelectionBackground": "#37373d",
  "list.inactiveSelectionForeground": "#cccccc",
  "editorActionList.background": "#1f1f1f",
  "editorActionList.foreground": "#cccccc",
  "editorActionList.focusBackground": "#04395e",
  "editorActionList.focusForeground": "#ffffff",
  "widget.shadow": "#00000080",
  "scrollbarSlider.background": "#79797966",
  "scrollbarSlider.hoverBackground": "#646464b3",
  "scrollbarSlider.activeBackground": "#bfbfbf66",
  "minimap.background": "#1f1f1f",
  "diffEditor.insertedTextBackground": "#9ccc2c33",
  "diffEditor.removedTextBackground": "#ff000033",
  "diffEditor.insertedLineBackground": "#9ccc2c22",
  "diffEditor.removedLineBackground": "#ff000022",
  "editorGutter.background": "#1f1f1f",
  "editorOverviewRuler.border": "#00000000",
  "editorBracketMatch.background": "#0064001a",
  "editorBracketMatch.border": "#888888",
};

const LIGHT_MODERN_CHROME: monaco.editor.IColors = {
  "editor.background": "#ffffff",
  "editor.foreground": "#3b3b3b",
  "editorLineNumber.foreground": "#6e7681",
  "editorLineNumber.activeForeground": "#171184",
  "editorCursor.foreground": "#000000",
  "editor.selectionBackground": "#add6ff",
  "editor.inactiveSelectionBackground": "#e5ebf1",
  "editor.lineHighlightBackground": "#f3f3f3",
  "editor.lineHighlightBorder": "#00000000",
  "editor.wordHighlightBackground": "#57575740",
  "editor.wordHighlightStrongBackground": "#0e639c40",
  "editor.findMatchBackground": "#a8ac94",
  "editor.findMatchHighlightBackground": "#ea5c0055",
  "editorIndentGuide.background": "#d3d3d3",
  "editorIndentGuide.activeBackground": "#939393",
  "editorWidget.background": "#f3f3f3",
  "editorWidget.border": "#cecece",
  "editorWidget.foreground": "#3b3b3b",
  "editorSuggestWidget.background": "#f3f3f3",
  "editorSuggestWidget.border": "#cecece",
  "editorSuggestWidget.selectedBackground": "#e8e8e8",
  "editorSuggestWidget.foreground": "#3b3b3b",
  "editorHoverWidget.background": "#f3f3f3",
  "editorHoverWidget.border": "#cecece",
  "editorHoverWidget.foreground": "#3b3b3b",
  "menu.background": "#ffffff",
  "menu.foreground": "#3b3b3b",
  "menu.border": "#cecece",
  "menu.separatorBackground": "#e5e5e5",
  "menu.selectionBackground": "#0060c0",
  "menu.selectionForeground": "#ffffff",
  "menu.selectionBorder": "#00000000",
  "list.hoverBackground": "#e8e8e8",
  "list.activeSelectionBackground": "#0060c0",
  "list.activeSelectionForeground": "#ffffff",
  "list.focusBackground": "#0060c0",
  "list.focusForeground": "#ffffff",
  "list.inactiveSelectionBackground": "#e4e6f1",
  "list.inactiveSelectionForeground": "#3b3b3b",
  "editorActionList.background": "#ffffff",
  "editorActionList.foreground": "#3b3b3b",
  "editorActionList.focusBackground": "#0060c0",
  "editorActionList.focusForeground": "#ffffff",
  "widget.shadow": "#00000029",
  "scrollbarSlider.background": "#64646466",
  "scrollbarSlider.hoverBackground": "#646464b3",
  "scrollbarSlider.activeBackground": "#00000066",
  "minimap.background": "#ffffff",
  "diffEditor.insertedTextBackground": "#9ccc2c40",
  "diffEditor.removedTextBackground": "#ff000033",
  "diffEditor.insertedLineBackground": "#9ccc2c22",
  "diffEditor.removedLineBackground": "#ff000022",
  "editorGutter.background": "#ffffff",
  "editorOverviewRuler.border": "#00000000",
  "editorBracketMatch.background": "#0064001a",
  "editorBracketMatch.border": "#b9b9b9",
};

const LIGHT_CHROME: monaco.editor.IColors = {
  "editor.background": "#faf9f7",
  "editor.foreground": "#1c1b19",
  "editorLineNumber.foreground": "#a8a39a",
  "editorLineNumber.activeForeground": "#5c5954",
  "editorCursor.foreground": "#8a6a2f",
  "editor.selectionBackground": "#e8d9b580",
  "editor.inactiveSelectionBackground": "#e8e4db66",
  "editor.lineHighlightBackground": "#eceae680",
  "editor.lineHighlightBorder": "#00000000",
  "editorIndentGuide.background": "#ddd9d1",
  "editorIndentGuide.activeBackground": "#c9c3b8",
  "editorWidget.background": "#faf9f7",
  "editorWidget.border": "#ddd9d1",
  "editorWidget.foreground": "#1c1b19",
  "editorSuggestWidget.background": "#faf9f7",
  "editorSuggestWidget.border": "#ddd9d1",
  "editorSuggestWidget.selectedBackground": "#e8e4db",
  "editorSuggestWidget.foreground": "#1c1b19",
  "editorHoverWidget.background": "#faf9f7",
  "editorHoverWidget.border": "#ddd9d1",
  "editorHoverWidget.foreground": "#1c1b19",
  "menu.background": "#faf9f7",
  "menu.foreground": "#5c5954",
  "menu.border": "#ddd9d1",
  "menu.separatorBackground": "#ddd9d1",
  "menu.selectionBackground": "#e8e4db",
  "menu.selectionForeground": "#5c5954",
  "menu.selectionBorder": "#00000000",
  "list.hoverBackground": "#eceae6",
  "list.activeSelectionBackground": "#e8e4db",
  "list.activeSelectionForeground": "#5c5954",
  "list.focusBackground": "#e8e4db",
  "list.focusForeground": "#5c5954",
  "list.inactiveSelectionBackground": "#eceae6",
  "list.inactiveSelectionForeground": "#1c1b19",
  "editorActionList.background": "#faf9f7",
  "editorActionList.foreground": "#5c5954",
  "editorActionList.focusBackground": "#e8e4db",
  "editorActionList.focusForeground": "#5c5954",
  "widget.shadow": "#1c1b1926",
  "scrollbarSlider.background": "#c9c3b866",
  "scrollbarSlider.hoverBackground": "#c9c3b899",
  "scrollbarSlider.activeBackground": "#c9c3b8cc",
  "minimap.background": "#faf9f7",
  "diffEditor.insertedTextBackground": "#d1fae580",
  "diffEditor.removedTextBackground": "#fee2e280",
  "diffEditor.insertedLineBackground": "#ecfdf580",
  "diffEditor.removedLineBackground": "#fef2f280",
  "editorGutter.background": "#faf9f7",
  "editorOverviewRuler.border": "#00000000",
};

function registerAnchorThemes(m: typeof monaco): void {
  if (themesRegistered) return;
  themesRegistered = true;

  m.editor.defineTheme("anchor-dark", {
    base: "vs-dark",
    inherit: true,
    rules: DARK_SYNTAX,
    colors: DARK_CHROME,
  });

  m.editor.defineTheme("anchor-dark-modern", {
    base: "vs-dark",
    inherit: true,
    rules: DARK_SYNTAX,
    colors: DARK_MODERN_CHROME,
  });

  m.editor.defineTheme("anchor-light-modern", {
    base: "vs",
    inherit: true,
    rules: LIGHT_SYNTAX,
    colors: LIGHT_MODERN_CHROME,
  });

  m.editor.defineTheme("anchor-light", {
    base: "vs",
    inherit: true,
    rules: LIGHT_SYNTAX,
    colors: LIGHT_CHROME,
  });
}

/**
 * Richer C/C++ Monarch tokenizer (no LSP).
 *
 * Type coloring is intentionally conservative:
 * - `comm_buffer_type_e`, `cam_hal_port_amba_t` → type
 * - `buffer_type` (parameter) → identifier (variable color), NOT type
 * - `CONTAINER_OF(...)` → macro
 * - `cam_hal_..._is_packet(...)` → function
 */
function cppLikeLanguage(isCpp: boolean): monaco.languages.IMonarchLanguage {
  const keywords = [
    "break",
    "case",
    "continue",
    "default",
    "do",
    "else",
    "for",
    "goto",
    "if",
    "return",
    "switch",
    "while",
    "sizeof",
    "typedef",
    "enum",
    "struct",
    "union",
    "const",
    "static",
    "extern",
    "volatile",
    "register",
    "inline",
    "restrict",
    "true",
    "false",
    "NULL",
    "nullptr",
    ...(isCpp
      ? [
          "class",
          "namespace",
          "template",
          "typename",
          "using",
          "public",
          "private",
          "protected",
          "virtual",
          "override",
          "final",
          "friend",
          "operator",
          "new",
          "delete",
          "this",
          "try",
          "catch",
          "throw",
          "noexcept",
          "constexpr",
          "consteval",
          "constinit",
          "decltype",
          "auto",
          "concept",
          "requires",
          "co_await",
          "co_return",
          "co_yield",
          "static_cast",
          "dynamic_cast",
          "const_cast",
          "reinterpret_cast",
          "static_assert",
          "export",
          "module",
          "import",
        ]
      : ["auto"]),
  ];

  const typeKeywords = [
    "void",
    "char",
    "short",
    "int",
    "long",
    "float",
    "double",
    "signed",
    "unsigned",
    "bool",
    "wchar_t",
    "char8_t",
    "char16_t",
    "char32_t",
    "size_t",
    "ssize_t",
    "ptrdiff_t",
    "intptr_t",
    "uintptr_t",
    "int8_t",
    "int16_t",
    "int32_t",
    "int64_t",
    "uint8_t",
    "uint16_t",
    "uint32_t",
    "uint64_t",
    "FILE",
    "va_list",
    ...(isCpp
      ? [
          "string",
          "wstring",
          "vector",
          "map",
          "unordered_map",
          "set",
          "unordered_set",
          "list",
          "array",
          "optional",
          "variant",
          "unique_ptr",
          "shared_ptr",
          "weak_ptr",
          "function",
          "tuple",
          "pair",
          "span",
          "string_view",
        ]
      : []),
  ];

  return {
    defaultToken: "",
    tokenPostfix: ".",
    keywords,
    typeKeywords,
    operators: [
      "=",
      ">",
      "<",
      "!",
      "~",
      "?",
      ":",
      "==",
      "<=",
      ">=",
      "!=",
      "&&",
      "||",
      "++",
      "--",
      "+",
      "-",
      "*",
      "/",
      "&",
      "|",
      "^",
      "%",
      "<<",
      ">>",
      "+=",
      "-=",
      "*=",
      "/=",
      "&=",
      "|=",
      "^=",
      "%=",
      "<<=",
      ">>=",
      "->",
      ".",
      "::",
    ],
    symbols: /[=><!~?:&|+\-*/^%]+/,
    escapes:
      /\\(?:[abfnrtv\\"']|x[0-9A-Fa-f]{1,4}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})/,
    tokenizer: {
      root: [
        [/^\s*#\s*\w+/, "keyword.directive"],
        [/[ \t\r\n]+/, ""],
        [/\/\*/, "comment", "@comment"],
        [/\/\/.*$/, "comment"],
        [/"([^"\\]|\\.)*$/, "string.invalid"],
        [/"/, "string", "@string"],
        [/'[^\\']'/, "string"],
        [/(')(@escapes)(')/, ["string", "string.escape", "string"]],
        [/'/, "string.invalid"],
        [/\d*\.\d+([eE][-+]?\d+)?[fFlL]?/, "number.float"],
        [/0[xX][0-9a-fA-F]+[uUlL]*/, "number.hex"],
        [/0[bB][01]+[uUlL]*/, "number.binary"],
        [/\d+[uUlL]*/, "number"],
        [/[{}()[\]]/, "@brackets"],
        [/[<>](?!@symbols)/, "@brackets"],
        [/@symbols/, "operator"],
        [/[,;.]/, "delimiter"],
        // Types: only explicit suffixes / keywords — never paint variables green.
        // Matches: AMBA_IMU_DATA_s, foo_t, bar_e, cam_handle — NOT
        // AmbaImuMpu6509VirtRingCtrl (global/struct instance, variable color).
        // do NOT match bare `_type` (would paint buffer_type).
        [
          /[a-zA-Z_]\w*_(?:t|e|s|st|et|tt|handle)\b/,
          "type",
        ],
        // SCREAMING_SNAKE macros / constants (CONTAINER_OF, MAX_PATH, UINT32)
        [/[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+\b/, "macro"],
        [/[A-Z][A-Z0-9_]{2,}\b/, "macro"],
        // Calls / definitions → function yellow (beats any remaining heuristics)
        [
          /[a-zA-Z_]\w*(?=\s*\()/,
          {
            cases: {
              "@keywords": "keyword",
              "@typeKeywords": "type",
              "@default": "function",
            },
          },
        ],
        // Everything else: keywords / built-in types / identifiers (variable blue)
        [
          /[a-zA-Z_]\w*/,
          {
            cases: {
              "@keywords": "keyword",
              "@typeKeywords": "type",
              "@default": "identifier",
            },
          },
        ],
      ],
      comment: [
        [/[^/*]+/, "comment"],
        [/\*\//, "comment", "@pop"],
        [/[/*]/, "comment"],
      ],
      string: [
        [/[^\\"]+/, "string"],
        [/@escapes/, "string.escape"],
        [/\\./, "string.escape.invalid"],
        [/"/, "string", "@pop"],
      ],
    },
  };
}

function registerLanguageExtras(m: typeof monaco): void {
  // Always re-apply so HMR / tokenizer tweaks take effect without full reload.
  m.languages.setMonarchTokensProvider("c", cppLikeLanguage(false));
  m.languages.setMonarchTokensProvider("cpp", cppLikeLanguage(true));
}

export function ensureMonacoConfigured(): void {
  if (!configured) {
    configured = true;

    self.MonacoEnvironment = {
      getWorker(_moduleId: string, label: string) {
        if (label === "json") return new jsonWorker();
        if (label === "css" || label === "scss" || label === "less") {
          return new cssWorker();
        }
        if (label === "html" || label === "handlebars" || label === "razor") {
          return new htmlWorker();
        }
        if (label === "typescript" || label === "javascript") {
          return new tsWorker();
        }
        return new editorWorker();
      },
    };

    loader.config({ monaco });
    registerAnchorThemes(monaco);
  }

  registerLanguageExtras(monaco);
}

// Configure as soon as this module is imported.
ensureMonacoConfigured();
